version: '3'

services:
  go-proxy-bingai:
    # 镜像名称
    image: adams549659584/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai  
    # 自启动
    restart: unless-stopped
    ports:
      - 8080:8080
  
#   go-proxy-bingai:
#     # 镜像名称
#     image: adams549659584/go-proxy-bingai
#     # 容器名称
#     container_name: go-proxy-bingai
#     build:
#       context: ../
#       dockerfile: docker/Dockerfile      
#     # 自启动
#     restart: unless-stopped
#     # 加入指定网络
#     networks:
#       - MyNetwork    
#     ports:
#       - 8888:8080        

# networks:
#   MyNetwork:
#     external: true

